spring:
  profiles:
    active: docker
---
spring:
  profiles: cloud
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-77.cfapps.io/eureka/
  instance:
    hostname: userInfo-77.cfapps.io
    nonSecurePort: 80
ribbon:
  eureka:
    enabled: true
aws:
  s3:
    url: https://s3.amazonaws.com/dataset-demos
---
spring:
  profiles: docker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./.h4/testdb
server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
aws:
  s3:
    url: http://localhost:9001
